name = "todo-daughter"
main = "src/worker/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "todo_daughter_db"
database_id = "0fc1b5e7-febd-432e-8728-87524b675dcb"
migrations_dir = "migrations"

# wrangler secret put JWT_SECRET
# wrangler secret put DAD_PASSWORD
# wrangler secret put DAUGHTER_PASSWORD
